analyzer:
  errors:
    deprecated_member_use: ignore

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_declarations: false
    avoid_print: false
    use_key_in_widget_constructors: true
    prefer_single_quotes: true
